# Generated by Django 5.2.7 on 2025-10-24 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='consultation',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor'), name='unique_patient_doctor_consultation'),
        ),
    ]
