# Generated by Django 5.2.7 on 2025-10-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_role_title'),
        ),
    ]
